# Generated by Django 5.2.6 on 2025-09-28 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nouvelle_postulation', 'Nouvelle postulation'), ('expiration_proche', 'Offre bientôt expirée'), ('annonce_admin', 'Annonce de l’administrateur'), ('recommandation_offre', 'Recommandation d’une offre'), ('autre', 'Autre')], max_length=20)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('lu', 'Lu'), ('non lu', 'Non lu')], default='non lu', max_length=10)),
                ('date_notif', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_possible', models.CharField(choices=[('accepter', 'Accepter'), ('refuser', 'Refuser'), ('aucune', 'Aucune'), ('voir', 'Voir')], default='aucune', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recu', to=settings.AUTH_USER_MODEL)),
                ('emetteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_emise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
