# Generated by Django 5.2.6 on 2025-10-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
