# Generated by Django 5.2.6 on 2025-10-26 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageries', '0002_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='utilisateur1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='utilisateur2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation2', to=settings.AUTH_USER_MODEL),
        ),
    ]
