# Generated by Django 5.2.6 on 2025-09-28 00:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('domaine', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Freelance', 'Freelance')], max_length=20)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expirée')], default='active', max_length=20)),
                ('lieu', models.CharField(blank=True, max_length=150, null=True)),
                ('horaire', models.CharField(blank=True, max_length=100, null=True)),
                ('salaire_propose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='comptes.employeur')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_abonnement', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_postulants', to='comptes.employeur')),
                ('postulant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='comptes.postulant')),
            ],
            options={
                'ordering': ['-date_abonnement'],
                'constraints': [models.UniqueConstraint(fields=('postulant', 'employeur'), name='unique_postulant_employeur')],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], default='debutant', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postulant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='comptes.postulant')),
            ],
            options={
                'ordering': ['libelle'],
                'constraints': [models.UniqueConstraint(fields=('postulant', 'libelle'), name='unique_postulant_competence')],
            },
        ),
        migrations.CreateModel(
            name='FavoriCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_candidats', to='comptes.employeur')),
                ('postulant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_par_employeurs', to='comptes.postulant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('employeur', 'postulant'), name='unique_employeur_postulant_favori')],
            },
        ),
        migrations.CreateModel(
            name='FavoriOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('postulant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_offres', to='comptes.postulant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='recrutements.offreemploi')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('postulant', 'offre'), name='unique_postulant_offre_favori')],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en attente', max_length=20)),
                ('postulant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='comptes.postulant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='recrutements.offreemploi')),
            ],
            options={
                'ordering': ['-date_candidature'],
                'constraints': [models.UniqueConstraint(fields=('postulant', 'offre'), name='unique_postulant_offre')],
            },
        ),
    ]
