# Generated by Django 5.2.6 on 2025-09-29 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        ('recrutements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('vue', 'Vue'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='comptes.employeur')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='recrutements.offreemploi')),
                ('postulant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations_recues', to='comptes.postulant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employeur', 'postulant', 'offre'), name='unique_recommandation')],
            },
        ),
    ]
