# Generated by Django 5.2.6 on 2025-10-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutements', '0002_recommandation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offreemploi',
            name='lieu',
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='arrondissement_emploie',
            field=models.CharField(choices=[('libreville_1', 'Libreville 1er'), ('libreville_2', 'Libreville 2e'), ('libreville_3', 'Libreville 3e'), ('owendo', 'Owendo'), ('akanda', 'Akanda'), ('ntoum', 'Ntoum')], default='libreville_1', max_length=50),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='prerequi_postulant',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='province_emploie',
            field=models.CharField(choices=[('estuaire', 'Estuaire'), ('haut_ogooué', 'Haut-Ogooué'), ('ngounié', 'Ngounié'), ('woleu_ntem', 'Woleu-Ntem'), ('nyanga', 'Nyanga'), ('ogooué_ivindo', 'Ogooué-Ivindo'), ('ogooué_lolo', 'Ogooué-Lolo'), ('ogooué_maritime', 'Ogooué-Maritime'), ('moyen_ogooué', 'Moyen-Ogooué')], default='estuaire', max_length=50),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='quartier',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
