# Generated by Django 5.2.6 on 2025-10-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recrutements', '0003_remove_offreemploi_lieu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offreemploi',
            old_name='quartier',
            new_name='quartier_emploie',
        ),
    ]
