# Generated by Django 5.2.6 on 2025-10-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recrutements', '0004_rename_quartier_offreemploi_quartier_emploie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommandation',
            name='message',
        ),
    ]
