# Generated by Django 5.2.6 on 2025-11-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutements', '0005_remove_recommandation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='nombre_vues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='province_emploie',
            field=models.CharField(choices=[('estuaire', 'Estuaire')], default='estuaire', max_length=50),
        ),
    ]
