# Generated by Django 5.2.6 on 2025-09-26 22:53

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raison_bannissement', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employeur', 'Employeur'), ('postulant', 'Postulant')], default='postulant', max_length=20)),
                ('photo', models.ImageField(blank=True, default='photos/default.png', null=True, upload_to='photos/')),
                ('nationalite', models.CharField(choices=[('GA', 'Gabonais(e)'), ('CM', 'Camerounais(e)'), ('CD', 'Congolais(e) (RDC)'), ('CG', 'Congolais(e) (RC)'), ('CI', 'Ivoirien(ne)'), ('SN', 'Sénégalais(e)'), ('ML', 'Malien(ne)'), ('BF', 'Burkinabé'), ('NE', 'Nigérien(ne)'), ('NG', 'Nigérian(e)'), ('TG', 'Togolais(e)'), ('BJ', 'Béninois(e)'), ('FR', 'Français(e)'), ('BE', 'Belge'), ('CA', 'Canadien(ne)'), ('US', 'Américain(e)'), ('BR', 'Brésilien(ne)'), ('IN', 'Indien(ne)'), ('CN', 'Chinois(e)'), ('JP', 'Japonais(e)'), ('DE', 'Allemand(e)'), ('ES', 'Espagnol(e)'), ('IT', 'Italien(ne)')], default='GA', max_length=10)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=5)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='GA')),
                ('date_naissance', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Postulant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('lettre_motivation', models.TextField(blank=True, null=True)),
                ('bio_postulant', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postulant', to='comptes.profil')),
            ],
            options={
                'verbose_name': 'Postulant',
                'verbose_name_plural': 'Postulants',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representant_entreprise', models.BooleanField(default=False)),
                ('nom_entreprise', models.CharField(blank=True, max_length=150, null=True)),
                ('secteur_activite', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('bio_entreprise', models.TextField(blank=True, null=True)),
                ('bio_employeur', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employeur', to='comptes.profil')),
            ],
            options={
                'verbose_name': 'Employeur',
                'verbose_name_plural': 'Employeurs',
                'ordering': ['nom_entreprise'],
            },
        ),
    ]
