# Generated by Django 5.2.6 on 2025-10-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeur',
            name='logo_entreprise',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
