# Generated by Django 5.2.6 on 2025-10-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_employeur_logo_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='arrondissement',
            field=models.CharField(choices=[('libreville_1', 'Libreville 1er'), ('libreville_2', 'Libreville 2e'), ('libreville_3', 'Libreville 3e'), ('owendo', 'Owendo'), ('akanda', 'Akanda'), ('ntoum', 'Ntoum')], default='libreville_1', max_length=50),
        ),
        migrations.AddField(
            model_name='profil',
            name='province',
            field=models.CharField(choices=[('estuaire', 'Estuaire'), ('haut_ogooué', 'Haut-Ogooué'), ('ngounié', 'Ngounié'), ('woleu_ntem', 'Woleu-Ntem'), ('nyanga', 'Nyanga'), ('ogooué_ivindo', 'Ogooué-Ivindo'), ('ogooué_lolo', 'Ogooué-Lolo'), ('ogooué_maritime', 'Ogooué-Maritime'), ('moyen_ogooué', 'Moyen-Ogooué')], default='estuaire', max_length=50),
        ),
        migrations.AddField(
            model_name='profil',
            name='quartier',
            field=models.CharField(default='Nzeng', max_length=150),
            preserve_default=False,
        ),
    ]
