# Generated by Django 5.2.6 on 2025-10-16 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_profil_arrondissement_profil_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('secteur_activite', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Société',
                'verbose_name_plural': 'Sociétés',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='employeur',
            options={'ordering': ['profil__user__username'], 'verbose_name': 'Employeur', 'verbose_name_plural': 'Employeurs'},
        ),
        migrations.RemoveField(
            model_name='employeur',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='employeur',
            name='bio_entreprise',
        ),
        migrations.RemoveField(
            model_name='employeur',
            name='logo_entreprise',
        ),
        migrations.RemoveField(
            model_name='employeur',
            name='nom_entreprise',
        ),
        migrations.RemoveField(
            model_name='employeur',
            name='secteur_activite',
        ),
        migrations.RemoveField(
            model_name='employeur',
            name='site_web',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='arrondissement',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='province',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='quartier',
        ),
        migrations.AddField(
            model_name='postulant',
            name='arrondissement',
            field=models.CharField(choices=[('libreville_1', 'Libreville 1er'), ('libreville_2', 'Libreville 2e'), ('libreville_3', 'Libreville 3e'), ('owendo', 'Owendo'), ('akanda', 'Akanda'), ('ntoum', 'Ntoum')], default='libreville_1', max_length=50),
        ),
        migrations.AddField(
            model_name='postulant',
            name='province',
            field=models.CharField(choices=[('estuaire', 'Estuaire'), ('haut_ogooué', 'Haut-Ogooué'), ('ngounié', 'Ngounié'), ('woleu_ntem', 'Woleu-Ntem'), ('nyanga', 'Nyanga'), ('ogooué_ivindo', 'Ogooué-Ivindo'), ('ogooué_lolo', 'Ogooué-Lolo'), ('ogooué_maritime', 'Ogooué-Maritime'), ('moyen_ogooué', 'Moyen-Ogooué')], default='estuaire', max_length=50),
        ),
        migrations.AddField(
            model_name='postulant',
            name='quartier',
            field=models.CharField(default='nzeng', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeur',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeurs', to='comptes.societe'),
        ),
    ]
