# Generated by Django 5.2.6 on 2025-10-16 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_societe_alter_employeur_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='societe',
            options={'ordering': ['nom_societe'], 'verbose_name': 'Société', 'verbose_name_plural': 'Sociétés'},
        ),
        migrations.RenameField(
            model_name='societe',
            old_name='adresse',
            new_name='adresse_societe',
        ),
        migrations.RenameField(
            model_name='societe',
            old_name='bio',
            new_name='bio_societe',
        ),
        migrations.RenameField(
            model_name='societe',
            old_name='logo',
            new_name='logo_societe',
        ),
        migrations.RenameField(
            model_name='societe',
            old_name='nom',
            new_name='nom_societe',
        ),
    ]
