# Generated by Django 5.2.6 on 2025-10-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_alter_societe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeur',
            name='representant_entreprise',
            field=models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='non', max_length=3),
        ),
    ]
