# Generated by Django 5.2.6 on 2025-10-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_alter_employeur_representant_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeur',
            name='representant_entreprise',
            field=models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3),
        ),
    ]
