# Generated by Django 5.2.6 on 2025-10-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_alter_employeur_representant_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='nom_societe',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
