# Generated by Django 5.2.6 on 2025-10-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0009_alter_societe_nom_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulant',
            name='introduction',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='quartier',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
