# Generated by Django 5.2.6 on 2025-10-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0010_postulant_introduction_alter_postulant_quartier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulant',
            old_name='introduction',
            new_name='intro_postulant',
        ),
    ]
