# Generated by Django 5.2.6 on 2025-11-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0011_rename_introduction_postulant_intro_postulant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulant',
            name='province',
            field=models.CharField(choices=[('estuaire', 'Estuaire')], default='estuaire', max_length=50),
        ),
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='photos/'),
        ),
    ]
